# Generated by Django 4.0.6 on 2022-07-26 14:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('price_compare', '0002_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7b7dcade-5cd6-4895-af42-15cff520d22e'), primary_key=True, serialize=False, unique=True),
        ),
    ]
