# Generated by Django 4.0.6 on 2022-07-26 16:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('price_compare', '0003_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8b5f2196-d815-47aa-8ff6-e7c1e4488293'), primary_key=True, serialize=False, unique=True),
        ),
    ]
