# Generated by Django 4.0.6 on 2022-07-26 18:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('price_compare', '0004_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fd74784d-9559-4245-98b8-43e155fed441'), primary_key=True, serialize=False, unique=True),
        ),
    ]
