# Generated by Django 4.0.6 on 2022-07-26 19:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('price_compare', '0004_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('18cc174c-a0d0-47d5-a0e9-962a0463d150'), primary_key=True, serialize=False, unique=True),
        ),
    ]
