# Generated by Django 4.0.6 on 2022-07-27 09:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('price_compare', '0005_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d527348b-76de-4a51-8f88-25153f46eb7b'), primary_key=True, serialize=False, unique=True),
        ),
    ]
