<<<<<<< HEAD
# Generated by Django 4.0.6 on 2022-07-27 09:46
=======
# Generated by Django 4.0.6 on 2022-07-26 19:37
>>>>>>> 14ef5b0e7e2c997cff48afb56caeac0d263683fa

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('price_compare', '0005_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
<<<<<<< HEAD
            field=models.UUIDField(default=uuid.UUID('d527348b-76de-4a51-8f88-25153f46eb7b'), primary_key=True, serialize=False, unique=True),
=======
            field=models.UUIDField(default=uuid.UUID('4cee53d2-7de2-49fb-ba61-d6af80953183'), primary_key=True, serialize=False, unique=True),
>>>>>>> 14ef5b0e7e2c997cff48afb56caeac0d263683fa
        ),
    ]
