# Generated by Django 4.0.6 on 2022-07-26 19:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('price_compare', '0005_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4cee53d2-7de2-49fb-ba61-d6af80953183'), primary_key=True, serialize=False, unique=True),
        ),
    ]
