# Generated by Django 4.0.6 on 2022-07-27 17:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('price_compare', '0006_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('265260a3-c27b-4107-bba8-dbbf12aa834d'), primary_key=True, serialize=False, unique=True),
        ),
    ]
