<<<<<<< HEAD
# Generated by Django 4.0.6 on 2022-07-27 17:27
=======
# Generated by Django 4.0.6 on 2022-07-27 11:33
>>>>>>> 14ef5b0e7e2c997cff48afb56caeac0d263683fa

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('price_compare', '0006_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
<<<<<<< HEAD
            field=models.UUIDField(default=uuid.UUID('265260a3-c27b-4107-bba8-dbbf12aa834d'), primary_key=True, serialize=False, unique=True),
=======
            field=models.UUIDField(default=uuid.UUID('c405c301-9c5c-4e88-8e6c-f0d7bbfb27fa'), primary_key=True, serialize=False, unique=True),
>>>>>>> 14ef5b0e7e2c997cff48afb56caeac0d263683fa
        ),
    ]
