# Generated by Django 4.0.6 on 2022-07-27 14:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('price_compare', '0007_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c20e00de-8ebc-49fd-aef8-b234e134e804'), primary_key=True, serialize=False, unique=True),
        ),
    ]
