# Generated by Django 4.0.6 on 2022-07-27 14:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('price_compare', '0008_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1929b234-f61d-422f-9f5f-832a66063cd8'), primary_key=True, serialize=False, unique=True),
        ),
    ]
