# Generated by Django 4.0.6 on 2022-07-28 13:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('price_compare', '0008_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('192965f5-8ff3-42ac-8523-4cac33b3714d'), primary_key=True, serialize=False, unique=True),
        ),
    ]
